#!/usr/bin/env python3
"""Chapter 7, Figure 7.4 -- LLM.int8() mixed-precision decomposition flow.

Replaces the original matplotlib figure generated by
`plot_decomposition_flow` in ch7_llm_int8_decomposition.py, which was
drawn at 14 x 5 inches with 8-10pt text.  Once fit to Manning's
5.6-inch column, that text shrank to ~3.6pt and became unreadable in
print.  This script redraws the same six-node flow diagram directly at
Manning dimensions with 7-8pt Arial, using matplotlib's patchA/patchB
auto-clipping so every arrow snaps cleanly to the visible edge of its
source/destination node -- the same pattern used in
ch5_decision_tree.py / ch5_qat_gantt.py.

Run:
    python ch7_llm_int8_flow.py
Outputs (in ch7/figures/):
    CH07_F04_Kalyanarangan.png
    CH07_F04_Kalyanarangan.pdf
    CH07_F04_Kalyanarangan.svg
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
from matplotlib.patches import FancyArrowPatch, FancyBboxPatch, Patch

# ---------------------------------------------------------------------------
# Manning layout constants
# ---------------------------------------------------------------------------
FIGURE_DIR = Path(__file__).parent / "figures"
FIG_BASE = "CH07_F04_Kalyanarangan"

FIG_W = 5.6   # inches (Manning column width)
FIG_H = 3.20  # inches

TITLE_FONT_SIZE = 9.5
NODE_FONT_SIZE = 7.5
EDGE_FONT_SIZE = 7.0
ANNOT_FONT_SIZE = 7.0

EDGE_COLOR = "#28253D"
TEXT_COLOR = "#28253D"
ACCENT_COLOR = "#1B5299"   # FP16 dashed-border accent (critical path)

# Node styles (subtle tinted fills, grayscale-safe -- matches
# ch5_decision_tree.py palette so Chapter 5 and Chapter 7 diagrams read
# as one visual family).
STYLE: Dict[str, Dict] = {
    "start":    {"fill": "#DCE6F5", "edge": EDGE_COLOR, "lw": 1.0, "ls": "-"},
    "decision": {"fill": "#FFF2C6", "edge": EDGE_COLOR, "lw": 1.0, "ls": "-"},
    "int8":     {"fill": "#DCE6F5", "edge": EDGE_COLOR, "lw": 1.0, "ls": "-"},
    "fp16":     {"fill": "#FFFFFF", "edge": ACCENT_COLOR, "lw": 1.2, "ls": "--"},
    "sum":      {"fill": "#E8E0F4", "edge": EDGE_COLOR, "lw": 1.0, "ls": "-"},
    "end":      {"fill": "#D6EDC8", "edge": EDGE_COLOR, "lw": 1.2, "ls": "-"},
}

Z_ARROW = 1
Z_NODE = 2
Z_EDGE_LABEL = 3


# ---------------------------------------------------------------------------
# Node data
# ---------------------------------------------------------------------------
@dataclass
class Node:
    name: str
    x: float
    y: float
    label: str
    kind: str            # one of STYLE keys
    w: float = 2.0
    h: float = 0.9


# Coordinate system: normal y-up (no invert).  xlim 0..12.5, ylim 0..7.15
# gives aspect 12.5/7.15 = 1.748, which matches FIG_W/FIG_H = 5.6/3.2
# = 1.75 so set_aspect("equal") leaves no ugly whitespace.
#
# Left-to-right flow:
#   X -> Detect -> [FP16 top / INT8 bottom] -> Sum -> Output
# Vertical budget: FP16/INT8 columns sit ~1.35 data units above/below
# centre so the top/bottom caption annotations still fit inside ylim.
NODES_LIST: List[Node] = [
    Node("X",        0.95, 3.60, "X\n[batch, d]",              "start",    w=1.55, h=1.00),
    Node("DETECT",   3.35, 3.60, "Detect\nOutliers\n|x| > 6.0", "decision", w=2.00, h=1.70),
    Node("FP16",     6.30, 5.25, "FP16 Matmul\n(~0.1% dims)",   "fp16",     w=2.35, h=1.05),
    Node("INT8",     6.30, 1.95, "INT8 Matmul\n(~99.9% dims)",  "int8",     w=2.35, h=1.05),
    Node("SUM",      9.10, 3.60, "\u03a3\nSum",                 "sum",      w=1.35, h=1.25),
    Node("OUT",     11.30, 3.60, "Output\n[batch, out]",        "end",      w=1.80, h=1.00),
]
NODES = {n.name: n for n in NODES_LIST}


# (src, dst, label, rad, dashed)
# rad > 0 curves one way, < 0 the other, 0 = straight chord.
# dashed=True draws the arrow with a dashed shaft (outlier / FP16 path).
EDGES: List[Tuple[str, str, Optional[str], float, bool]] = [
    ("X",      "DETECT", None,           0.00, False),
    ("DETECT", "FP16",   "outlier cols", 0.00, True),
    ("DETECT", "INT8",   "normal cols",  0.00, False),
    ("FP16",   "SUM",    None,           0.00, True),
    ("INT8",   "SUM",    None,           0.00, False),
    ("SUM",    "OUT",    None,           0.00, False),
]


# ---------------------------------------------------------------------------
# Drawing
# ---------------------------------------------------------------------------
def draw_node(ax, n: Node) -> Patch:
    style = STYLE[n.kind]
    patch: Patch = FancyBboxPatch(
        (n.x - n.w / 2, n.y - n.h / 2),
        n.w,
        n.h,
        boxstyle="round,pad=0,rounding_size=0.18",
        facecolor=style["fill"],
        edgecolor=style["edge"],
        linewidth=style["lw"],
        linestyle=style["ls"],
        zorder=Z_NODE,
    )
    ax.add_patch(patch)
    # Label weight: a touch bolder for FP16/INT8 so the path names read
    # first when scanning the figure.
    fontweight = "bold" if n.kind in ("fp16", "int8", "sum") else "normal"
    ax.text(
        n.x, n.y, n.label,
        ha="center", va="center",
        fontsize=NODE_FONT_SIZE, color=TEXT_COLOR,
        fontweight=fontweight,
        linespacing=1.10,
        zorder=Z_NODE + 0.5,
    )
    return patch


def draw_edge(
    ax,
    src: Node,
    dst: Node,
    src_patch: Patch,
    dst_patch: Patch,
    label: Optional[str],
    rad: float = 0.0,
    dashed: bool = False,
) -> None:
    """Draw an arrow using patchA/patchB so it snaps to each node's visible edge."""
    arrow = FancyArrowPatch(
        (src.x, src.y),
        (dst.x, dst.y),
        connectionstyle=f"arc3,rad={rad}",
        arrowstyle="-|>,head_length=6,head_width=4",
        linewidth=0.9,
        color=EDGE_COLOR,
        linestyle="--" if dashed else "-",
        patchA=src_patch,
        patchB=dst_patch,
        shrinkA=0.5,
        shrinkB=0.5,
        zorder=Z_ARROW,
    )
    ax.add_patch(arrow)

    if not label:
        return

    # Straight-line label: sit slightly above the midpoint and biased
    # toward the source, so the arrowhead end stays free.
    mx = src.x * 0.55 + dst.x * 0.45
    my = src.y * 0.55 + dst.y * 0.45
    if rad != 0.0:
        dx = dst.x - src.x
        dy = dst.y - src.y
        length = (dx * dx + dy * dy) ** 0.5 or 1.0
        px = -dy / length
        py = dx / length
        offset = rad * (length / 2.0)
        mx += px * offset
        my += py * offset

    ax.text(
        mx, my, label,
        ha="center", va="center",
        fontsize=EDGE_FONT_SIZE, color=TEXT_COLOR,
        fontstyle="italic",
        bbox=dict(
            boxstyle="round,pad=0.15",
            facecolor="white",
            edgecolor="none",
        ),
        zorder=Z_EDGE_LABEL,
    )


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
def main() -> None:
    plt.rcParams.update({
        "font.family": "sans-serif",
        "font.sans-serif": ["Arial", "Helvetica", "DejaVu Sans"],
        "font.size": NODE_FONT_SIZE,
        "savefig.dpi": 300,
    })

    fig, ax = plt.subplots(figsize=(FIG_W, FIG_H))
    # Let the axes fill the entire figure so the output is exactly
    # FIG_W x FIG_H after saving (we skip bbox_inches="tight" on save
    # to avoid whitespace trimming that would shrink the figure below
    # the Manning column width).
    fig.subplots_adjust(left=0.01, right=0.99, top=0.90, bottom=0.02)
    ax.set_xlim(-0.10, 12.50)
    ax.set_ylim(-0.05, 7.15)
    ax.set_aspect("equal")
    ax.axis("off")

    patches: Dict[str, Patch] = {}
    for n in NODES_LIST:
        patches[n.name] = draw_node(ax, n)

    for src_name, dst_name, label, rad, dashed in EDGES:
        draw_edge(
            ax,
            NODES[src_name],
            NODES[dst_name],
            patches[src_name],
            patches[dst_name],
            label,
            rad,
            dashed,
        )

    # Annotations above FP16 / below INT8, matching the original figure.
    ax.text(
        6.30, 6.55,
        "Zero quantization error on critical dimensions",
        ha="center", va="center",
        fontsize=ANNOT_FONT_SIZE, color=ACCENT_COLOR,
        fontstyle="italic",
        zorder=Z_EDGE_LABEL,
    )
    ax.text(
        6.30, 0.55,
        "Per-channel weights \u00d7 per-token activations\n"
        "3 orders of magnitude less error than per-tensor",
        ha="center", va="center",
        fontsize=ANNOT_FONT_SIZE, color=ACCENT_COLOR,
        fontstyle="italic",
        linespacing=1.15,
        zorder=Z_EDGE_LABEL,
    )

    fig.suptitle(
        "LLM.int8() Mixed-Precision Decomposition Flow",
        fontsize=TITLE_FONT_SIZE,
        fontweight="bold",
        color=TEXT_COLOR,
        y=0.96,
    )

    FIGURE_DIR.mkdir(parents=True, exist_ok=True)
    png_path = FIGURE_DIR / f"{FIG_BASE}.png"
    pdf_path = FIGURE_DIR / f"{FIG_BASE}.pdf"
    svg_path = FIGURE_DIR / f"{FIG_BASE}.svg"
    # Save without bbox_inches="tight" so FIG_W x FIG_H is preserved
    # exactly -- Manning wants figures at column width, not shrunk.
    fig.savefig(png_path, dpi=300)
    fig.savefig(pdf_path)
    fig.savefig(svg_path)
    plt.close(fig)
    print(f"Saved:\n  {png_path}\n  {pdf_path}\n  {svg_path}")


if __name__ == "__main__":
    main()
