"""Render configs for the local observability stack (Pushgateway, Prometheus, Grafana).

Reads secrets from observability/secrets/ (generated by gen_tls_and_secret.py)
and writes configs that:
  * bind every component to 127.0.0.1 (no LAN exposure)
  * enforce TLS on the Pushgateway with the self-signed cert
  * require Basic auth on the Pushgateway (bcrypt-hashed)
  * point Prometheus at the Pushgateway over HTTPS, verifying the cert
  * stand Grafana on a private home dir with no anonymous access

The Grafana admin password is generated fresh by this script (CSPRNG) and
written to observability/secrets/grafana.admin (0600). It is passed to
Grafana via the GF_SECURITY_ADMIN_PASSWORD env var by run_stack.sh —
never embedded in grafana.ini.
"""
from __future__ import annotations

import json
import os
import secrets
import sys
from pathlib import Path

BASE = Path(__file__).resolve().parent
TLS_DIR = BASE / "tls"
SEC_DIR = BASE / "secrets"

PG_DIR    = BASE / "pushgateway"
PROM_DIR  = BASE / "prometheus"
GRAF_DIR  = BASE / "grafana"
PG_DIR.mkdir(exist_ok=True)
PROM_DIR.mkdir(exist_ok=True)
(PROM_DIR / "data").mkdir(exist_ok=True)
GRAF_DIR.mkdir(exist_ok=True)
(GRAF_DIR / "data").mkdir(exist_ok=True)
(GRAF_DIR / "logs").mkdir(exist_ok=True)
(GRAF_DIR / "plugins").mkdir(exist_ok=True)
(GRAF_DIR / "provisioning" / "datasources").mkdir(parents=True, exist_ok=True)
(GRAF_DIR / "provisioning" / "dashboards").mkdir(parents=True, exist_ok=True)


def _read_secret(name: str) -> str:
    p = SEC_DIR / name
    if not p.exists():
        raise SystemExit(f"missing {p}; run gen_tls_and_secret.py first")
    return p.read_text().strip()


def _write(path: Path, text: str, mode: int = 0o600) -> None:
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, mode)
    with os.fdopen(fd, "w") as f:
        f.write(text)
    os.chmod(path, mode)


def main() -> None:
    user = _read_secret("push.user")
    bhash = _read_secret("push.bcrypt")

    # ---- Pushgateway web config: TLS + basic auth, loopback only ----
    # YAML single-quoted scalars escape internal "'" by doubling; bcrypt
    # hashes don't contain single quotes, so direct interpolation is safe.
    # We still assert that property at runtime to fail closed.
    if "'" in user or "'" in bhash:
        raise SystemExit("unexpected single-quote in credentials; refusing to embed.")
    pg_web = f"""# Pushgateway web config (TLS + basic auth, loopback only)
tls_server_config:
  cert_file: {TLS_DIR / 'server.crt'}
  key_file:  {TLS_DIR / 'server.key'}
  min_version: TLS12

basic_auth_users:
  '{user}': '{bhash}'
"""
    _write(PG_DIR / "web.yml", pg_web, mode=0o600)

    # ---- Prometheus config: scrape pushgateway over https w/ ca_file ----
    prom = f"""# Local Prometheus for ch12 device session
global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: pushgateway
    honor_labels: true
    scheme: https
    static_configs:
      - targets: ['127.0.0.1:9091']
    basic_auth:
      username: {user}
      password_file: {SEC_DIR / 'push.password'}
    tls_config:
      ca_file: {TLS_DIR / 'server.crt'}
      server_name: localhost
"""
    _write(PROM_DIR / "prometheus.yml", prom, mode=0o600)

    # ---- Grafana admin password (CSPRNG, never logged) ----
    admin_path = SEC_DIR / "grafana.admin"
    if not admin_path.exists():
        admin_pw = secrets.token_urlsafe(24)
        fd = os.open(admin_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(fd, "w") as f:
            f.write(admin_pw)

    # ---- Grafana INI: bind to loopback, disable anonymous, no signups ----
    grafana_ini = f"""# ch12 local Grafana — loopback only, no anonymous, no signups
[paths]
data         = {GRAF_DIR / 'data'}
logs         = {GRAF_DIR / 'logs'}
plugins      = {GRAF_DIR / 'plugins'}
provisioning = {GRAF_DIR / 'provisioning'}

[server]
protocol   = http
http_addr  = 127.0.0.1
http_port  = 3000

[security]
admin_user      = admin
disable_gravatar = true
cookie_secure   = false
cookie_samesite = lax
strict_transport_security = false
content_security_policy = true

[auth.anonymous]
enabled = false

[users]
allow_sign_up = false
allow_org_create = false

[analytics]
reporting_enabled = false
check_for_updates = false
"""
    _write(GRAF_DIR / "grafana.ini", grafana_ini, mode=0o600)

    # ---- Grafana datasource provisioning ----
    ds = """apiVersion: 1
datasources:
  - name: ch12_prom
    type: prometheus
    access: proxy
    url: http://127.0.0.1:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "5s"
"""
    _write(GRAF_DIR / "provisioning" / "datasources" / "prometheus.yml", ds, mode=0o600)

    # ---- Grafana dashboard provisioning pointer ----
    dboard_yml = f"""apiVersion: 1
providers:
  - name: ch12-device
    orgId: 1
    folder: ''
    type: file
    disableDeletion: false
    updateIntervalSeconds: 30
    allowUiUpdates: true
    options:
      path: {GRAF_DIR / 'provisioning' / 'dashboards'}
"""
    _write(GRAF_DIR / "provisioning" / "dashboards" / "ch12_device.yml",
           dboard_yml, mode=0o600)

    # ---- Dashboard JSON ----
    dashboard = {
      "annotations": {"list": []},
      "editable": True,
      "fiscalYearStartMonth": 0,
      "graphTooltip": 0,
      "id": None,
      "links": [],
      "liveNow": False,
      "panels": [
        {
          "datasource": {"type": "prometheus", "uid": "ch12_prom"},
          "fieldConfig": {"defaults": {"unit": "ms", "decimals": 3}, "overrides": []},
          "gridPos": {"h": 9, "w": 12, "x": 0, "y": 0},
          "id": 1,
          "title": "Stage latency (ms)",
          "type": "timeseries",
          "targets": [{
            "expr": 'ch12_device_stage_latency_ms{job="ch12_device_vision"}',
            "legendFormat": "{{stage}}",
            "refId": "A"
          }],
        },
        {
          "datasource": {"type": "prometheus", "uid": "ch12_prom"},
          "fieldConfig": {"defaults": {"unit": "ms"}, "overrides": []},
          "gridPos": {"h": 9, "w": 12, "x": 12, "y": 0},
          "id": 2,
          "title": "End-to-end p95 (ms)",
          "type": "timeseries",
          "targets": [{
            "expr": 'ch12_device_e2e_p95_ms{job="ch12_device_vision"}',
            "legendFormat": "p95",
            "refId": "A"
          }],
        },
        {
          "datasource": {"type": "prometheus", "uid": "ch12_prom"},
          "fieldConfig": {"defaults": {"unit": "watt", "decimals": 3}, "overrides": []},
          "gridPos": {"h": 8, "w": 8, "x": 0, "y": 9},
          "id": 3,
          "title": "Estimated power (W) — powermetrics, not sensor-grade",
          "type": "stat",
          "targets": [{
            "expr": 'ch12_device_power_w_estimated{job="ch12_device_vision"}',
            "refId": "A"
          }],
        },
        {
          "datasource": {"type": "prometheus", "uid": "ch12_prom"},
          "fieldConfig": {"defaults": {"unit": "percentunit", "min": 0, "max": 1}, "overrides": []},
          "gridPos": {"h": 8, "w": 8, "x": 8, "y": 9},
          "id": 4,
          "title": "Op placement (ANE/GPU/CPU)",
          "type": "piechart",
          "options": {"legend": {"displayMode": "list", "placement": "right", "values": ["value"]}},
          "targets": [{
            "expr": 'ch12_device_op_placement_frac{job="ch12_device_vision"}',
            "legendFormat": "{{unit}}",
            "refId": "A"
          }],
        },
        {
          "datasource": {"type": "prometheus", "uid": "ch12_prom"},
          "fieldConfig": {"defaults": {"unit": "percent", "min": 0, "max": 110}, "overrides": []},
          "gridPos": {"h": 8, "w": 8, "x": 16, "y": 9},
          "id": 5,
          "title": "Thermal retention (last-30s / first-30s, %)",
          "type": "gauge",
          "targets": [{
            "expr": 'ch12_device_thermal_retention_pct{job="ch12_device_vision"}',
            "refId": "A"
          }],
        },
      ],
      "refresh": "5s",
      "schemaVersion": 38,
      "tags": ["ch12", "device"],
      "templating": {"list": []},
      "time": {"from": "now-15m", "to": "now"},
      "timepicker": {},
      "timezone": "",
      "title": "ch12_device_vision",
      "uid": "ch12-device-vision",
      "version": 1,
      "weekStart": "",
    }
    _write(
        GRAF_DIR / "provisioning" / "dashboards" / "ch12_device_vision.json",
        json.dumps(dashboard, indent=2),
        mode=0o600,
    )

    print("wrote pushgateway/web.yml")
    print("wrote prometheus/prometheus.yml")
    print("wrote grafana/grafana.ini")
    print("wrote grafana/provisioning/datasources/prometheus.yml")
    print("wrote grafana/provisioning/dashboards/ch12_device.yml")
    print("wrote grafana/provisioning/dashboards/ch12_device_vision.json")


if __name__ == "__main__":
    main()
